packages:
  - packages/*
  - examples/*

catalog:
  "@effect/platform-node": ^0.106.0
  "@effect/platform": ^0.96.2
  "@types/node": "^24.13.3"
  "@types/react-dom": ^19.2.3
  "@types/react": ^19.2.17
  "@vitejs/plugin-react": ^6.0.3
  "@vitest/browser-playwright": ^4.1.10
  "@vitest/browser": ^4.1.10
  "effect": ^3.21.4
  "oauth2-mock-server": ^9.1.0
  "playwright": ^1.60.0
  "react-dom": ^19.2.7
  "react": ^19.2.7
  "type-fest": ^5.8.0
  "typescript": ~7.0.2
  "vite": ^8.1.4
  "vitest": ^4.1.10

allowBuilds:
  "@parcel/watcher": false
  msgpackr-extract: false

minimumReleaseAge: 4320

verifyDepsBeforeRun: warn
