packages:
  - packages/*
  - examples/*

catalog:
  "@effect/platform-node": ^0.106.0
  "@effect/platform": ^0.96.1
  "@types/node": "24"
  "@vitest/browser-playwright": ^4.1.7
  "@vitest/browser": ^4.1.7
  "effect": ^3.21.2
  "oauth2-mock-server": ^9.0.0
  "playwright": ^1.60.0
  "type-fest": ^5.6.0
  "typescript": ~6.0.3
  "vite": ^8.0.11
  "vitest": ^4.1.7

allowBuilds:
  "@parcel/watcher": false
  msgpackr-extract: false

minimumReleaseAge: 4320
