name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm type-check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm fmt --check

  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  test:
    needs: test-matrix
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: needs.test-matrix.result != 'success'
